"use client";

import { FileText, HelpCircle, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { loadAcProvenance, type AcProvenance } from "@/lib/ac-generation-client";
import { openSourceDocumentVersion } from "@/lib/source-documents-client";

// Source provenance of a canonical Acceptance Criterion promoted from an AI
// proposal (Phase 1F): AC → proposal → generation run → Requirement →
// source fragments → document version → document, plus the Human
// Clarifications, scope notes and resolved generation issues it relies on.
// Read-only and shown to every role (authoritative facts only — no working
// AI content). Renders a short note for ACs that were created manually.

const when = (value: string | null | undefined) =>
  value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const pagesOf = (f: { page_start: number | null; page_end: number | null }) =>
  f.page_start == null ? null : f.page_end != null && f.page_end !== f.page_start ? `pp. ${f.page_start}–${f.page_end}` : `p. ${f.page_start}`;
const ORIGIN: Record<string, string> = { ai: "AI proposal", split: "proposal split by a reviewer", merge: "proposal merged by a reviewer", manual: "human-authored proposal" };

export function AcProvenancePanel({ projectId, acId }: { projectId: string; acId: string }) {
  const [provenance, setProvenance] = useState<AcProvenance | null | undefined>(undefined);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    loadAcProvenance(projectId, acId)
      .then((r) => { if (live) setProvenance(r.provenance); })
      .catch((e) => { if (live) setError(e instanceof Error ? e.message : "Could not load the source provenance."); });
    return () => { live = false; };
  }, [projectId, acId]);

  if (error) return <p className="text-xs text-destructive">{error}</p>;
  if (provenance === undefined) return <p className="text-xs text-muted-foreground">Loading source provenance…</p>;
  if (provenance === null) return <p className="text-xs text-muted-foreground">Created manually — no AI source provenance.</p>;
  const { proposal, generation_run: run, requirement, fragments, scope_notes, human_clarifications, resolved_issues } = provenance;
  const doc = provenance.requirement_provenance?.document, version = provenance.requirement_provenance?.version;
  const isPdf = version?.content_type === "application/pdf";
  const open = (page: number | null) => {
    if (!version) return;
    openSourceDocumentVersion(projectId, version.id, "inline", isPdf ? page : null).catch((e) => setError(e instanceof Error ? e.message : "Could not open the original."));
  };

  return (
    <section aria-label="Source provenance" className="space-y-2 rounded-md border p-3 text-xs">
      <p className="flex items-center gap-1.5 font-semibold uppercase text-muted-foreground"><FileText className="h-3.5 w-3.5" aria-hidden="true" />Source provenance</p>
      <p>
        Promoted from {ORIGIN[proposal.origin] ?? "proposal"} #{proposal.sequence} for <span className="font-medium">{requirement?.requirement_ref ?? "Requirement"}</span> by {proposal.promoted_by_name ?? "—"}, {when(proposal.promoted_at)}
        {proposal.confirmed_by_name ? ` · reviewed and confirmed by ${proposal.confirmed_by_name}` : ""}
      </p>
      <p className="text-muted-foreground">
        {doc?.document_name ?? "Source document"} v{version?.version_number ?? "?"}{run ? ` · generated by ${run.model}, AC prompts ${run.prompt_version ?? "—"}` : ""}
      </p>
      <ul className="space-y-1.5">
        {fragments.map((f) => (
          <li key={f.id} className="rounded border bg-muted/30 p-2">
            <div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{f.section_path?.length ? f.section_path.join(" › ") : f.section_heading ?? "Document start"}</span><span className="text-muted-foreground">{pagesOf(f) ?? "not paginated"}</span></div>
            <p className="mt-1 line-clamp-3 whitespace-pre-wrap text-muted-foreground">{f.text}</p>
            {isPdf && f.page_start ? <button type="button" className="mt-1 text-primary underline" onClick={() => open(f.page_start)}>Open original at page {f.page_start}</button> : null}
          </li>
        ))}
      </ul>
      {human_clarifications.length ? (
        <ul className="space-y-1">
          {human_clarifications.map((c) => <li key={c.id}><HelpCircle className="mr-1 inline h-3 w-3" aria-hidden="true" /><span className="font-medium">Relies on Human Clarification:</span> {c.clarification} <span className="text-muted-foreground">— {c.created_by_name}, {when(c.created_at)}</span></li>)}
        </ul>
      ) : null}
      {scope_notes.length ? <ul className="space-y-1">{scope_notes.map((n) => <li key={n.id}><ShieldCheck className="mr-1 inline h-3 w-3" aria-hidden="true" />Scope note: {n.area ? `${n.area}: ` : ""}{n.description}</li>)}</ul> : null}
      {resolved_issues.length ? <ul className="space-y-1">{resolved_issues.map((i) => <li key={i.id}>{i.status} question ({i.issue_type}): {i.resolution_note ?? "—"}{i.reviewed_by_name ? ` — ${i.reviewed_by_name}` : ""}</li>)}</ul> : null}
      <p className="text-muted-foreground">This acceptance criterion was created from an approved AI proposal, so it cannot be deleted — its promotion history must be preserved. Change its status instead.</p>
    </section>
  );
}
