import {
  AlertTriangle,
  BookOpenCheck,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  CalendarRange,
  CircleHelp,
  ClipboardCheck,
  FileText,
  Flag,
  GitBranch,
  History,
  LayoutDashboard,
  ListChecks,
  MessageSquareText,
  Mail,
  Newspaper,
  PackageCheck,
  PanelsTopLeft,
  Settings,
  ShieldQuestion,
  Stethoscope,
  TrendingUp,
} from "lucide-react";
import type { ComponentType, SVGProps } from "react";
import type { EntityName } from "@/lib/types";

export type ModuleConfig = {
  key: EntityName;
  slug: string;
  title: string;
  singular: string;
  description: string;
  icon: ComponentType<SVGProps<SVGSVGElement>>;
  statusField?: string;
  searchFields: string[];
  filterFields?: string[];
  columns: { key: string; label: string; type?: "status" | "priority" | "date" | "impact" }[];
  fields: { key: string; label: string; type?: "textarea" | "date" | "number" | "select"; options?: string[]; required?: boolean; min?: number; max?: number; refPrefix?: string; rows?: number; badge?: boolean }[];
};

export const navItems = [
  { href: "/", label: "Dashboard", icon: LayoutDashboard },
  { href: "/project-workspace", label: "Project Workspace", icon: PanelsTopLeft },
  { href: "/project-intelligence", label: "Project Intelligence", icon: BrainCircuit },
  { href: "/daily-brief", label: "Daily Brief", icon: Newspaper },
  { href: "/project-trends", label: "Project Trends", icon: TrendingUp },
  { href: "/projects", label: "Projects", icon: BriefcaseBusiness },
  { href: "/deliverables", label: "Deliverables", icon: PackageCheck },
  { href: "/requirements", label: "Requirements", icon: ListChecks },
  { href: "/risks", label: "Risks", icon: AlertTriangle },
  { href: "/decisions", label: "Decisions", icon: ShieldQuestion },
  { href: "/discovery-questions", label: "Discovery Questions", icon: CircleHelp },
  { href: "/actions", label: "Actions", icon: ClipboardCheck },
  { href: "/milestones", label: "Milestones", icon: Flag },
  { href: "/timeline", label: "Timeline", icon: CalendarRange },
  { href: "/dependencies", label: "Dependencies", icon: GitBranch },
  { href: "/testing", label: "Testing", icon: BookOpenCheck },
  { href: "/meetings", label: "Meetings", icon: CalendarDays },
  { href: "/documents", label: "Documents", icon: FileText },
  { href: "/audit-trail", label: "Audit Trail", icon: History },
  { href: "/system-health", label: "System Health", icon: Stethoscope },
  { href: "/email-settings", label: "Email Settings", icon: Mail },
  { href: "/settings", label: "Settings", icon: Settings },
];

const statusOptions = ["Discovery", "Open", "In Progress", "Pending", "Blocked", "Approved", "Complete", "Closed"];
const requirementSourceOptions = [
  "Functional Specification",
  "Technical Design",
  "Customer Workshop",
  "Discovery Question",
  "Business Decision",
  "Email",
  "Existing Solution",
  "Current Process Documentation",
  "Test Strategy",
  "SIT",
  "UAT",
  "Customer Request",
  "Other",
];
const priorityOptions = ["Low", "Medium", "High", "Critical"];
const requirementCategoryOptions = ["Business Rule", "Database", "Backend", "UI", "Performance", "Testing"];
const discoveryStatusOptions = ["Open", "Awaiting Business", "Awaiting Development", "Awaiting Response", "Answered", "Closed"];
const discoveryCategoryOptions = ["Business Rule", "Replenishment Logic", "Database", "Performance", "Testing", "UI"];
const milestoneStatusOptions = ["Not Started", "In Progress", "Complete", "At Risk", "Blocked"];
const timelineStatusOptions = ["Not Started", "In Progress", "Complete", "At Risk", "Blocked"];
const testStatusOptions = ["Pending", "In Progress", "Passed", "Failed", "Blocked"];
const deliverableStatusOptions = ["Not Started", "In Analysis", "In Development", "Ready for SIT", "SIT Complete", "Ready for UAT", "UAT Complete", "Ready for Deployment", "Deployed", "Blocked"];
const developmentStatusOptions = ["Not Started", "In Analysis", "In Development", "Complete", "Blocked"];
const assuranceStatusOptions = ["Not Started", "Ready", "In Progress", "Passed", "Failed", "Blocked"];
const deploymentStatusOptions = ["Not Started", "Ready", "Scheduled", "Deployed", "Blocked"];

export const modules: ModuleConfig[] = [
  {
    key: "projects",
    slug: "projects",
    title: "Projects",
    singular: "Project",
    description: "Manage the active project and workstream context.",
    icon: BriefcaseBusiness,
    searchFields: ["name", "customer", "workstream", "status"],
    columns: [
      { key: "name", label: "Project" },
      { key: "customer", label: "Customer" },
      { key: "workstream", label: "Workstream" },
      { key: "health", label: "Health", type: "status" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "name", label: "Project name" },
      { key: "customer", label: "Customer" },
      { key: "workstream", label: "Workstream" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "health", label: "Project health", type: "select", options: ["Green", "Amber", "Red"] },
      { key: "planned_start_date", label: "Planned start date", type: "date" },
      { key: "planned_end_date", label: "Planned end date", type: "date" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "deliverables",
    slug: "deliverables",
    title: "Deliverables",
    singular: "Deliverable",
    description: "Track solution scope through development, SIT, UAT and deployment.",
    icon: PackageCheck,
    searchFields: ["deliverable_ref", "title", "workstream", "owner", "priority", "status"],
    columns: [
      { key: "deliverable_ref", label: "Ref" },
      { key: "title", label: "Deliverable" },
      { key: "workstream", label: "Workstream" },
      { key: "priority", label: "Priority", type: "priority" },
      { key: "status", label: "Status", type: "status" },
      { key: "planned_completion_date", label: "Planned", type: "date" },
      { key: "owner", label: "Owner" },
    ],
    fields: [
      { key: "deliverable_ref", label: "Deliverable ref", required: true, refPrefix: "DEL" },
      { key: "title", label: "Title", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "workstream", label: "Workstream", required: true },
      { key: "owner", label: "Owner" },
      { key: "priority", label: "Priority", type: "select", options: priorityOptions, required: true },
      { key: "status", label: "Status", type: "select", options: deliverableStatusOptions, required: true },
      { key: "planned_completion_date", label: "Planned completion date", type: "date" },
      { key: "actual_completion_date", label: "Actual completion date", type: "date" },
      { key: "development_status", label: "Development status", type: "select", options: developmentStatusOptions, required: true },
      { key: "sit_status", label: "SIT status", type: "select", options: assuranceStatusOptions, required: true },
      { key: "uat_status", label: "UAT status", type: "select", options: assuranceStatusOptions, required: true },
      { key: "deployment_status", label: "Deployment status", type: "select", options: deploymentStatusOptions, required: true },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "requirements",
    slug: "requirements",
    title: "Requirements",
    singular: "Requirement",
    description: "Track CR028 Replenishment requirements from discovery through approval.",
    icon: ListChecks,
    searchFields: ["requirement_ref", "title", "owner", "source", "status"],
    filterFields: ["source", "category", "status", "priority", "owner"],
    columns: [
      { key: "requirement_ref", label: "Ref" },
      { key: "title", label: "Requirement" },
      { key: "priority", label: "Priority", type: "priority" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status", type: "status" },
      { key: "owner", label: "Owner" },
    ],
    fields: [
      { key: "requirement_ref", label: "Reference", refPrefix: "REP" },
      { key: "title", label: "Title" },
      { key: "description", label: "Description", type: "textarea", rows: 5 },
      { key: "priority", label: "Priority", type: "select", options: priorityOptions },
      { key: "category", label: "Category", type: "select", options: requirementCategoryOptions },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "owner", label: "Owner" },
      { key: "source", label: "Source", type: "select", options: requirementSourceOptions, badge: true },
      { key: "notes", label: "Notes", type: "textarea", rows: 4 },
    ],
  },
  {
    key: "risks",
    slug: "risks",
    title: "Risks",
    singular: "Risk",
    description: "Monitor delivery, data volume and replenishment logic risks.",
    icon: AlertTriangle,
    searchFields: ["risk_ref", "description", "owner", "status"],
    columns: [
      { key: "risk_ref", label: "Ref" },
      { key: "description", label: "Risk" },
      { key: "impact", label: "Impact", type: "impact" },
      { key: "probability", label: "Probability" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "risk_ref", label: "Reference", refPrefix: "RSK" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "impact", label: "Impact", type: "select", options: priorityOptions },
      { key: "probability", label: "Probability", type: "select", options: ["Low", "Medium", "High"] },
      { key: "mitigation", label: "Mitigation", type: "textarea" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  {
    key: "decisions",
    slug: "decisions",
    title: "Decisions",
    singular: "Decision",
    description: "Keep open design and business decisions visible.",
    icon: ShieldQuestion,
    searchFields: ["decision_ref", "question", "decision", "owner", "status"],
    columns: [
      { key: "decision_ref", label: "Ref" },
      { key: "question", label: "Question" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "status" },
      { key: "due_date", label: "Due", type: "date" },
    ],
    fields: [
      { key: "decision_ref", label: "Reference", refPrefix: "DEC" },
      { key: "question", label: "Question", type: "textarea" },
      { key: "decision", label: "Decision", type: "textarea" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "decision_date", label: "Decision date", type: "date" },
      { key: "due_date", label: "Due date", type: "date" },
    ],
  },
  {
    key: "discovery_questions",
    slug: "discovery-questions",
    title: "Discovery Questions",
    singular: "Discovery Question",
    description: "Track unanswered business and technical questions through discovery.",
    icon: CircleHelp,
    searchFields: ["question_ref", "question", "owner", "category", "status"],
    columns: [
      { key: "question_ref", label: "Ref" },
      { key: "question", label: "Question" },
      { key: "category", label: "Category" },
      { key: "owner", label: "Owner" },
      { key: "due_date", label: "Due", type: "date" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "question_ref", label: "Reference", refPrefix: "QUE" },
      { key: "question", label: "Question", type: "textarea" },
      { key: "owner", label: "Owner" },
      { key: "category", label: "Category", type: "select", options: discoveryCategoryOptions },
      { key: "status", label: "Status", type: "select", options: discoveryStatusOptions },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "answer", label: "Answer", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "raised_to", label: "Raised to (email)" },
      { key: "raised_date", label: "Raised date", type: "date" },
      { key: "response", label: "Response", type: "textarea" },
      { key: "answered_by", label: "Answered by" },
      { key: "answered_date", label: "Answered date", type: "date" },
    ],
  },
  {
    key: "actions",
    slug: "actions",
    title: "Actions",
    singular: "Action",
    description: "Track ownership, due dates and overdue follow-up.",
    icon: ClipboardCheck,
    searchFields: ["action_ref", "description", "owner", "status"],
    columns: [
      { key: "action_ref", label: "Ref" },
      { key: "description", label: "Action" },
      { key: "owner", label: "Owner" },
      { key: "due_date", label: "Due", type: "date" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "action_ref", label: "Reference", refPrefix: "ACT" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "owner", label: "Owner" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "milestones",
    slug: "milestones",
    title: "Milestones",
    singular: "Milestone",
    description: "Track delivery gates, target dates and milestone health.",
    icon: Flag,
    searchFields: ["milestone_ref", "title", "owner", "status"],
    columns: [
      { key: "milestone_ref", label: "Ref" },
      { key: "title", label: "Milestone" },
      { key: "target_date", label: "Target", type: "date" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "milestone_ref", label: "Reference", refPrefix: "MIL" },
      { key: "title", label: "Title" },
      { key: "target_date", label: "Target date", type: "date" },
      { key: "status", label: "Status", type: "select", options: milestoneStatusOptions },
      { key: "owner", label: "Owner" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "timeline_items",
    slug: "timeline",
    title: "Timeline",
    singular: "Timeline Item",
    description: "Manage delivery phases, dates, ownership and schedule progress.",
    icon: CalendarRange,
    statusField: "status",
    searchFields: ["phase_ref", "phase_name", "owner", "status", "notes"],
    columns: [
      { key: "phase_ref", label: "Ref" },
      { key: "phase_name", label: "Phase" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "progress_percent", label: "Progress %" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { key: "phase_ref", label: "Phase reference", required: true, refPrefix: "PHS" },
      { key: "phase_name", label: "Phase name", required: true },
      { key: "start_date", label: "Start date", type: "date", required: true },
      { key: "end_date", label: "End date", type: "date", required: true },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: timelineStatusOptions, required: true },
      { key: "progress_percent", label: "Progress percent", type: "number", required: true, min: 0, max: 100 },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "dependencies",
    slug: "dependencies",
    title: "Dependencies",
    singular: "Dependency",
    description: "Track technical and process dependencies for the workstream.",
    icon: GitBranch,
    searchFields: ["name", "owner", "status", "notes"],
    columns: [
      { key: "name", label: "Dependency" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes" },
    ],
    fields: [
      { key: "name", label: "Name" },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: statusOptions },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "test_cases",
    slug: "testing",
    title: "Testing",
    singular: "Test Case",
    description: "Plan focused date-range replenishment validation.",
    icon: BookOpenCheck,
    searchFields: ["test_ref", "scenario", "owner", "status"],
    columns: [
      { key: "test_ref", label: "Ref" },
      { key: "scenario", label: "Scenario" },
      { key: "status", label: "Status", type: "status" },
      { key: "owner", label: "Owner" },
    ],
    fields: [
      { key: "test_ref", label: "Reference", refPrefix: "TST" },
      { key: "scenario", label: "Scenario", type: "textarea" },
      { key: "expected_result", label: "Expected result", type: "textarea" },
      { key: "actual_result", label: "Actual result", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: testStatusOptions },
      { key: "owner", label: "Owner" },
    ],
  },
  {
    key: "meetings",
    slug: "meetings",
    title: "Meetings",
    singular: "Meeting",
    description: "Capture meeting notes, decisions and actions.",
    icon: CalendarDays,
    searchFields: ["title", "attendees", "notes", "meeting_date"],
    columns: [
      { key: "meeting_date", label: "Date", type: "date" },
      { key: "title", label: "Title" },
      { key: "attendees", label: "Attendees" },
      { key: "actions", label: "Actions" },
    ],
    fields: [
      { key: "meeting_date", label: "Meeting date", type: "date" },
      { key: "title", label: "Title" },
      { key: "attendees", label: "Attendees" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "decisions", label: "Decisions", type: "textarea" },
      { key: "actions", label: "Actions", type: "textarea" },
    ],
  },
  {
    key: "documents",
    slug: "documents",
    title: "Documents",
    singular: "Document",
    description: "Record document references. Document upload will be added in v2.",
    icon: FileText,
    searchFields: ["document_name", "document_type", "notes"],
    columns: [
      { key: "document_name", label: "Document" },
      { key: "document_type", label: "Type" },
      { key: "uploaded_at", label: "Uploaded", type: "date" },
      { key: "notes", label: "Notes" },
    ],
    fields: [
      { key: "document_name", label: "Document name" },
      { key: "document_type", label: "Type" },
      { key: "storage_path", label: "Storage path" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
];

export const moduleBySlug = new Map(modules.map((config) => [config.slug, config]));
export const moduleByKey = new Map(modules.map((config) => [config.key, config]));

export const settingsModule = {
  title: "Settings",
  icon: MessageSquareText,
};
